import 'package:smart_home/src/models/safety/safety_model.dart';

const safetyFloorLabels = {'floor1': 'Floor 1'};
const safetyRoomLabels = {
  'living': 'Living Room',
  'kitchen': 'Kitchen',
  'bedroom1': 'Bedroom 1',
  'bathroom1': 'Bathroom 1',
};
const safetyDeviceTypeLabels = {
  SafetyDeviceType.smoke: 'Smoke alarm',
  SafetyDeviceType.heat: 'Heat sensor',
  SafetyDeviceType.carbonMonoxide: 'CO alarm',
  SafetyDeviceType.waterLeak: 'Water leak sensor',
  SafetyDeviceType.door: 'Door sensor',
  SafetyDeviceType.window: 'Window sensor',
  SafetyDeviceType.motion: 'Motion sensor',
};

const sampleSafetyDevices = [
  SafetyDevice(
      id: 'smoke-1',
      title: 'Smoke alarm',
      type: SafetyDeviceType.smoke,
      floorId: 'floor1',
      roomId: 'kitchen',
      location: 'Kitchen ceiling',
      state: SafetyDeviceState.normal,
      isOnline: true,
      batteryPercent: 92),
  SafetyDevice(
      id: 'heat-1',
      title: 'Heat sensor',
      type: SafetyDeviceType.heat,
      floorId: 'floor1',
      roomId: 'kitchen',
      location: 'Cooking area',
      state: SafetyDeviceState.normal,
      isOnline: true,
      batteryPercent: 86,
      temperatureC: 22),
  SafetyDevice(
      id: 'co-1',
      title: 'CO alarm',
      type: SafetyDeviceType.carbonMonoxide,
      floorId: 'floor1',
      roomId: 'living',
      location: 'Hallway',
      state: SafetyDeviceState.normal,
      isOnline: true,
      batteryPercent: 94),
  SafetyDevice(
      id: 'leak-1',
      title: 'Water leak sensor',
      type: SafetyDeviceType.waterLeak,
      floorId: 'floor1',
      roomId: 'bathroom1',
      location: 'Under the basin',
      state: SafetyDeviceState.dry,
      isOnline: true,
      batteryPercent: 81),
  SafetyDevice(
      id: 'door-1',
      title: 'Front door',
      type: SafetyDeviceType.door,
      floorId: 'floor1',
      roomId: 'living',
      location: 'Entrance',
      state: SafetyDeviceState.closed,
      isOnline: true,
      batteryPercent: 92,
      isLocked: true),
  SafetyDevice(
      id: 'window-1',
      title: 'Kitchen window',
      type: SafetyDeviceType.window,
      floorId: 'floor1',
      roomId: 'kitchen',
      location: 'Above the counter',
      state: SafetyDeviceState.open,
      isOnline: true,
      batteryPercent: 78),
  SafetyDevice(
      id: 'motion-1',
      title: 'Hallway motion',
      type: SafetyDeviceType.motion,
      floorId: 'floor1',
      roomId: 'living',
      location: 'Hallway',
      state: SafetyDeviceState.clear,
      isOnline: true,
      batteryPercent: 88),
  SafetyDevice(
      id: 'window-2',
      title: 'Bedroom window',
      type: SafetyDeviceType.window,
      floorId: 'floor1',
      roomId: 'bedroom1',
      location: 'Beside the bed',
      state: SafetyDeviceState.closed,
      isOnline: true,
      batteryPercent: 85),
  SafetyDevice(
      id: 'window-3',
      title: 'Balcony door',
      type: SafetyDeviceType.door,
      floorId: 'floor1',
      roomId: 'living',
      location: 'Balcony entrance',
      state: SafetyDeviceState.closed,
      isOnline: true,
      batteryPercent: 90),
  SafetyDevice(
      id: 'motion-2',
      title: 'Bedroom motion',
      type: SafetyDeviceType.motion,
      floorId: 'floor1',
      roomId: 'bedroom1',
      location: 'Bedroom ceiling',
      state: SafetyDeviceState.clear,
      isOnline: true,
      batteryPercent: 89),
];

const sampleSafetyEvents = [
  SafetyEvent(
      id: 'event-1',
      title: 'Kitchen window opened',
      description: 'The kitchen window contact reported open.',
      timeLabel: 'Today, 14:20',
      type: SafetyDeviceType.window,
      deviceId: 'window-1',
      floorId: 'floor1',
      roomId: 'kitchen'),
  SafetyEvent(
      id: 'event-2',
      title: 'Front door locked',
      description: 'The front door reported a locked state.',
      timeLabel: 'Today, 13:48',
      type: SafetyDeviceType.door,
      deviceId: 'door-1',
      floorId: 'floor1',
      roomId: 'living'),
  SafetyEvent(
      id: 'event-3',
      title: 'Smoke alarm online',
      description: 'The smoke alarm reconnected and reported normal.',
      timeLabel: 'Today, 13:05',
      type: SafetyDeviceType.smoke,
      deviceId: 'smoke-1',
      floorId: 'floor1',
      roomId: 'kitchen'),
  SafetyEvent(
      id: 'event-4',
      title: 'Motion detected',
      description: 'Hallway motion was detected; the sensor now reports clear.',
      timeLabel: 'Today, 12:32',
      type: SafetyDeviceType.motion,
      deviceId: 'motion-1',
      floorId: 'floor1',
      roomId: 'living'),
  SafetyEvent(
      id: 'event-5',
      title: 'Bedroom window closed',
      description: 'The bedroom window contact reported closed.',
      timeLabel: 'Yesterday, 21:15',
      type: SafetyDeviceType.window,
      deviceId: 'window-2',
      floorId: 'floor1',
      roomId: 'bedroom1'),
];
